; inspired by pokecrystal/constants/landmark_constants.asm
; order based on map_constants
	const_def
	const LANDMARK_PALLET_TOWN          ; $00
	const LANDMARK_VIRIDIAN_CITY        ; $01
	const LANDMARK_PEWTER_CITY          ; $02
	const LANDMARK_CERULEAN_CITY        ; $03
	const LANDMARK_LAVENDER_TOWN        ; $04
	const LANDMARK_VERMILION_CITY       ; $05
	const LANDMARK_CELADON_CITY         ; $06
	const LANDMARK_FUCHSIA_CITY         ; $07
	const LANDMARK_CINNABAR_ISLAND      ; $08
	const LANDMARK_INDIGO_PLATEAU       ; $09
	const LANDMARK_SAFFRON_CITY         ; $0A
	const LANDMARK_ROUTE_1              ; $0B
	const LANDMARK_ROUTE_2              ; $0C
	const LANDMARK_ROUTE_3              ; $0D
	const LANDMARK_ROUTE_4              ; $0E
	const LANDMARK_ROUTE_5              ; $0F
	const LANDMARK_ROUTE_6              ; $10
	const LANDMARK_ROUTE_7              ; $11
	const LANDMARK_ROUTE_8              ; $12
	const LANDMARK_ROUTE_9              ; $13
	const LANDMARK_ROUTE_10             ; $14
	const LANDMARK_ROUTE_11             ; $15
	const LANDMARK_ROUTE_12             ; $16
	const LANDMARK_ROUTE_13             ; $17
	const LANDMARK_ROUTE_14             ; $18
	const LANDMARK_ROUTE_15             ; $19
	const LANDMARK_ROUTE_16             ; $1A
	const LANDMARK_ROUTE_17             ; $1B
	const LANDMARK_ROUTE_18             ; $1C
	const LANDMARK_ROUTE_19             ; $1D
	const LANDMARK_ROUTE_20             ; $1E
	const LANDMARK_ROUTE_21             ; $1F
	const LANDMARK_ROUTE_22             ; $20
	const LANDMARK_ROUTE_23             ; $21
	const LANDMARK_ROUTE_24             ; $22
	const LANDMARK_ROUTE_25             ; $23
	const LANDMARK_DIGLETTS_CAVE        ; $24
	const LANDMARK_VIRIDIAN_FOREST      ; $25
	const LANDMARK_MT_MOON              ; $26
	const LANDMARK_ROCK_TUNNEL          ; $27
	const LANDMARK_POWER_PLANT          ; $28
	const LANDMARK_VICTORY_ROAD         ; $29
	const LANDMARK_SEAFOAM_ISLANDS      ; $2A
	const LANDMARK_POKEMON_MANSION      ; $2B
	const LANDMARK_SAFARI_ZONE          ; $2C
	const LANDMARK_CERULEAN_CAVE        ; $2D
DEF NUM_LANDMARKS EQU const_value
