; inspired by pokecrystal/constants/landmark_constants.asm
; order based on map_constants
	const_def
	const LANDMARK_PALLET_TOWN          ;$00
	const LANDMARK_VIRIDIAN_CITY        ;$01
	const LANDMARK_PEWTER_CITY          ;$02
	const LANDMARK_CERULEAN_CITY        ;$03
	const LANDMARK_LAVENDER_TOWN        ;$04
	const LANDMARK_VERMILION_CITY       ;$05
	const LANDMARK_CELADON_CITY         ;$06
	const LANDMARK_FUCHSIA_CITY         ;$07
	const LANDMARK_CINNABAR_ISLAND      ;$08
	const LANDMARK_INDIGO_PLATEAU       ;$09
	const LANDMARK_SAFFRON_CITY         ;$0A
	const LANDMARK_ROUTE_1              ;$0B
	const LANDMARK_ROUTE_2              ;$0C
	const LANDMARK_ROUTE_3              ;$0D
	const LANDMARK_ROUTE_4              ;$0E
	const LANDMARK_ROUTE_5              ;$0F
	const LANDMARK_ROUTE_6              ;$10
	const LANDMARK_ROUTE_7              ;$11
	const LANDMARK_ROUTE_8              ;$12
	const LANDMARK_ROUTE_9              ;$13
	const LANDMARK_ROUTE_10             ;$14
	const LANDMARK_ROUTE_11             ;$15
	const LANDMARK_ROUTE_12             ;$16
	const LANDMARK_ROUTE_13             ;$17
	const LANDMARK_ROUTE_14             ;$18
	const LANDMARK_ROUTE_15             ;$19
	const LANDMARK_ROUTE_16             ;$1A
	const LANDMARK_ROUTE_17             ;$1B
	const LANDMARK_ROUTE_18             ;$1C
	const LANDMARK_ROUTE_19             ;$1D
	const LANDMARK_ROUTE_20             ;$1E
	const LANDMARK_ROUTE_21             ;$1F
	const LANDMARK_ROUTE_22             ;$20
	const LANDMARK_ROUTE_23             ;$21
	const LANDMARK_ROUTE_24             ;$22
	const LANDMARK_ROUTE_25             ;$23
	const LANDMARK_OAKS_LAB             ;$24
	const LANDMARK_VIRIDIAN_GYM         ;$25
	const LANDMARK_DIGLETTS_CAVE        ;$26
	const LANDMARK_VIRIDIAN_FOREST      ;$27
	const LANDMARK_PEWTER_GYM           ;$28
	const LANDMARK_MT_MOON_1F           ;$29
	const LANDMARK_MT_MOON_B1F          ;$2A
	const LANDMARK_MT_MOON_B2F          ;$2B
	const LANDMARK_CERULEAN_GYM         ;$2C
	const LANDMARK_ROCK_TUNNEL_1F       ;$2D
	const LANDMARK_POWER_PLANT          ;$2E
	const LANDMARK_VERMILION_GYM        ;$2F
	const LANDMARK_VERMILION_DOCK       ;$30
	const LANDMARK_VICTORY_ROAD_1F      ;$31
	const LANDMARK_LANCES_ROOM          ;$32
	const LANDMARK_CHAMPIONS_ROOM       ;$33
	const LANDMARK_CELADON_GYM          ;$34
	const LANDMARK_POKEMON_TOWER_3F     ;$35
	const LANDMARK_POKEMON_TOWER_4F     ;$36
	const LANDMARK_POKEMON_TOWER_5F     ;$37
	const LANDMARK_POKEMON_TOWER_6F     ;$38
	const LANDMARK_POKEMON_TOWER_7F     ;$39
	const LANDMARK_FUCHSIA_GYM          ;$3A
	const LANDMARK_SEAFOAM_ISLANDS_B1F  ;$3B
	const LANDMARK_SEAFOAM_ISLANDS_B2F  ;$3C
	const LANDMARK_SEAFOAM_ISLANDS_B3F  ;$3D
	const LANDMARK_SEAFOAM_ISLANDS_B4F  ;$3E
	const LANDMARK_POKEMON_MANSION_1F   ;$3F
	const LANDMARK_CINNABAR_GYM         ;$40
	const LANDMARK_SAFFRON_GYM          ;$41
	const LANDMARK_SEAFOAM_ISLANDS_1F   ;$42
	const LANDMARK_VICTORY_ROAD_2F      ;$43
	const LANDMARK_VICTORY_ROAD_3F      ;$44
	const LANDMARK_POKEMON_MANSION_2F   ;$45
	const LANDMARK_POKEMON_MANSION_3F   ;$46
	const LANDMARK_POKEMON_MANSION_B1F  ;$47
	const LANDMARK_SAFARI_ZONE_EAST     ;$48
	const LANDMARK_SAFARI_ZONE_NORTH    ;$49
	const LANDMARK_SAFARI_ZONE_WEST     ;$4A
	const LANDMARK_SAFARI_ZONE_CENTER   ;$4B
	const LANDMARK_CERULEAN_CAVE_2F     ;$4C
	const LANDMARK_CERULEAN_CAVE_B1F    ;$4D
	const LANDMARK_CERULEAN_CAVE_1F     ;$4E
	const LANDMARK_ROCK_TUNNEL_B1F      ;$4F
	const LANDMARK_LORELEIS_ROOM        ;$50
	const LANDMARK_BRUNOS_ROOM          ;$51
	const LANDMARK_AGATHAS_ROOM         ;$52
DEF NUM_LANDMARKS EQU const_value
