EvolutionIndexTable: ; takes POKEMON_INDEXES and points them to EVOLUTION
	db $02, EVOLUTION_RHYDON      ; RHYDON
	db $03, EVOLUTION_KANGASKHAN  ; KANGASKHAN
	db $04, EVOLUTION_NIDOKING    ; NIDORAN_M
	db $05, EVOLUTION_CLEFABLE    ; CLEFAIRY
	db $06, EVOLUTION_FEAROW      ; SPEAROW
	db $07, EVOLUTION_ELECTRODE   ; VOLTORB
	db $08, EVOLUTION_NIDOKING    ; NIDOKING
	db $09, EVOLUTION_SLOWBRO     ; SLOWBRO
	db $0A, EVOLUTION_VENUSAUR    ; IVYSAUR
	db $0B, EVOLUTION_EXEGGUTOR   ; EXEGGUTOR
	db $0C, EVOLUTION_LICKITUNG   ; LICKITUNG
	db $0D, EVOLUTION_EXEGGUTOR   ; EXEGGCUTE
	db $0E, EVOLUTION_MUK         ; GRIMER
	db $0F, EVOLUTION_GENGAR      ; GENGAR
	db $11, EVOLUTION_NIDOQUEEN   ; NIDORAN_F, NIDOQUEEN
	db $12, EVOLUTION_MAROWAK     ; CUBONE
	db $13, EVOLUTION_RHYDON      ; RHYHORN
	db $14, EVOLUTION_LAPRAS      ; LAPRAS
	db $15, EVOLUTION_ARCANINE    ; ARCANINE
	db $16, EVOLUTION_MEW         ; MEW
	db $17, EVOLUTION_GYARADOS    ; GYARADOS
	db $18, EVOLUTION_CLOYSTER    ; SHELLDER
	db $19, EVOLUTION_TENTACRUEL  ; TENTACOOL
	db $1A, EVOLUTION_GENGAR      ; GASTLY
	db $1B, EVOLUTION_SCYTHER     ; SCYTHER
	db $1C, EVOLUTION_STARMIE     ; STARYU
	db $1D, EVOLUTION_BLASTOISE   ; BLASTOISE
	db $1E, EVOLUTION_PINSIR      ; PINSIR
	db $1F, EVOLUTION_TANGELA     ; TANGELA
	db $22, EVOLUTION_ARCANINE    ; $1F, $20, GROWLITHE
	db $23, EVOLUTION_ONIX        ; ONIX
	db $24, EVOLUTION_FEAROW      ; FEAROW
	db $25, EVOLUTION_PIDGEOT     ; PIDGEY
	db $26, EVOLUTION_SLOWBRO     ; SLOWPOKE
	db $27, EVOLUTION_ALAKAZAM    ; KADABRA
	db $28, EVOLUTION_GOLEM       ; GRAVELER
	db $29, EVOLUTION_CHANSEY     ; CHANSEY
	db $2A, EVOLUTION_MACHAMP     ; MACHOKE
	db $2B, EVOLUTION_MR_MIME     ; MR_MIME
	db $2C, EVOLUTION_HITMONLEE   ; HITMONLEE
	db $2D, EVOLUTION_HITMONCHAN  ; HITMONCHAN
	db $2E, EVOLUTION_ARBOK       ; ARBOK
	db $2F, EVOLUTION_PARASECT    ; PARASECT
	db $30, EVOLUTION_GOLDUCK     ; PSYDUCK
	db $31, EVOLUTION_HYPNO       ; DROWZEE
	db $32, EVOLUTION_GOLEM       ; GOLEM
	db $34, EVOLUTION_MAGMAR      ; $32, MAGMAR
	db $36, EVOLUTION_ELECTABUZZ  ; $34, ELECTABUZZ
	db $37, EVOLUTION_MAGNETON    ; MAGNETON
	db $38, EVOLUTION_WEEZING     ; KOFFING
	db $3A, EVOLUTION_PRIMEAPE    ; $38, MANKEY
	db $3B, EVOLUTION_DEWGONG     ; SEEL
	db $3C, EVOLUTION_DUGTRIO     ; DIGLETT
	db $3D, EVOLUTION_TAUROS      ; TAUROS
	db $41, EVOLUTION_FARFETCHD   ; $3D, $3E, $3F, FARFETCHD
	db $42, EVOLUTION_VENOMOTH    ; VENONAT
	db $43, EVOLUTION_DRAGONITE   ; DRAGONITE
	db $47, EVOLUTION_DODRIO      ; $43, $44, $45, DODUO
	db $48, EVOLUTION_POLIWRATH   ; POLIWAG
	db $49, EVOLUTION_JYNX        ; JYNX
	db $4A, EVOLUTION_MOLTRES     ; MOLTRES
	db $4B, EVOLUTION_ARTICUNO    ; ARTICUNO
	db $4C, EVOLUTION_ZAPDOS      ; ZAPDOS
	db $4D, EVOLUTION_DITTO       ; DITTO
	db $4E, EVOLUTION_PERSIAN     ; MEOWTH
	db $4F, EVOLUTION_KINGLER     ; KRABBY
	db $54, EVOLUTION_NINETALES   ; $4F, $50, $51, VULPIX, NINETALES
	db $56, EVOLUTION_RAICHU      ; PIKACHU, RAICHU
	db $5A, EVOLUTION_DRAGONITE   ; $56, $57, DRATINI, DRAGONAIR
	db $5C, EVOLUTION_KABUTOPS    ; KABUTO, KABUTOPS
	db $5E, EVOLUTION_SEADRA      ; HORSEA, SEADRA
	db $62, EVOLUTION_SANDSLASH   ; $5E, $5F, SANDSHREW, SANDSLASH
	db $64, EVOLUTION_OMASTAR     ; OMANYTE, OMASTAR
	db $66, EVOLUTION_WIGGLYTUFF  ; JIGGLYPUFF, WIGGLYTUFF
	db $6A, EVOLUTION_EEVEE       ; EEVEE, FLAREON, JOLTEON, VAPOREON
	db $6B, EVOLUTION_MACHAMP     ; MACHOP
	db $6C, EVOLUTION_GOLBAT      ; ZUBAT
	db $6D, EVOLUTION_ARBOK       ; EKANS
	db $6E, EVOLUTION_PARASECT    ; PARAS
	db $70, EVOLUTION_POLIWRATH   ; POLIWHIRL, POLIWRATH
	db $73, EVOLUTION_BEEDRILL    ; WEEDLE, KAKUNA, BEEDRILL
	db $75, EVOLUTION_DODRIO      ; $73, DODRIO
	db $76, EVOLUTION_PRIMEAPE    ; PRIMEAPE
	db $77, EVOLUTION_DUGTRIO     ; DUGTRIO
	db $78, EVOLUTION_VENOMOTH    ; VENOMOTH
	db $79, EVOLUTION_DEWGONG     ; DEWGONG
	db $7E, EVOLUTION_BUTTERFREE  ; $79, $7A, CATERPIE, METAPOD, BUTTERFREE
	db $7F, EVOLUTION_MACHAMP     ; MACHAMP
	db $81, EVOLUTION_GOLDUCK     ; GOLDUCK
	db $82, EVOLUTION_HYPNO       ; HYPNO
	db $83, EVOLUTION_GOLBAT      ; GOLBAT
	db $84, EVOLUTION_MEWTWO      ; MEWTWO
	db $85, EVOLUTION_SNORLAX     ; SNORLAX
	db $86, EVOLUTION_GYARADOS    ; MAGIKARP
	db $89, EVOLUTION_MUK         ; $86, $87, MUK
	db $8B, EVOLUTION_KINGLER     ; $89, KINGLER
	db $8C, EVOLUTION_CLOYSTER    ; CLOYSTER
	db $8E, EVOLUTION_ELECTRODE   ; $8C, ELECTRODE
	db $8F, EVOLUTION_CLEFABLE    ; CLEFABLE
	db $90, EVOLUTION_WEEZING     ; WEEZING
	db $91, EVOLUTION_PERSIAN     ; PERSIAN
	db $92, EVOLUTION_MAROWAK     ; MAROWAK
	db $94, EVOLUTION_GENGAR      ; $92, HAUNTER
	db $96, EVOLUTION_ALAKAZAM    ; ABRA, ALAKAZAM
	db $98, EVOLUTION_PIDGEOT     ; PIDEOTTO, PIDGEOT
	db $99, EVOLUTION_STARMIE     ; STARMIE
	db $9B, EVOLUTION_VENUSAUR    ; BULBASAUR, VENUSAUR
	db $9C, EVOLUTION_TENTACRUEL  ; TENTACRUEL
	db $9F, EVOLUTION_SEAKING     ; $9C, GOLDEEN, SEAKING
	db $A5, EVOLUTION_RAPIDASH    ; $9F, $A0, $A1, $A2, PONYTA, RAPIDASH
	db $A7, EVOLUTION_RATICATE    ; RATTATA, RATICATE
	db $A8, EVOLUTION_NIDOKING    ; NIDORINO
	db $A9, EVOLUTION_NIDOQUEEN   ; NIDOQUEEN
	db $AA, EVOLUTION_GOLEM       ; GEODUDE
	db $AB, EVOLUTION_PORYGON     ; PORYGON
	db $AC, EVOLUTION_AERODACTYL  ; AERODACTYL
	db $AE, EVOLUTION_MAGNETON    ; MAGNEMITE
	db $B1, EVOLUTION_CHARIZARD   ; $AE, $AF, CHARMANDER
	db $B2, EVOLUTION_BLASTOISE   ; SQUIRTLE
	db $B3, EVOLUTION_CHARIZARD   ; CHARMELEON
	db $B4, EVOLUTION_BLASTOISE   ; WARTORTLE
	db $B5, EVOLUTION_CHARIZARD   ; CHARIZARD
	db $BC, EVOLUTION_VILEPLUME   ; $B5, FOSSIL_KABUTOPS, FOSSIL_AERODACTYL, MON_GHOST, ODDISH, GLOOM, VILEPLUME
	db $BF, EVOLUTION_VICTREEBEL  ; BELLSPROUT, WEEPINBELL, VICTREEBEL
	db $FF
